CREATE TABLE MANAGER_SUMMARY (
MANAGER_ID NUMBER,
DEPARTMENT_ID NUMBER,
MANAGER_NAME VARCHAR2(100),
DIRECT_REPORT_COUNT NUMBER,
GENERATED_BY VARCHAR2(30),
GENERATED_ON DATE
);

-- SQL FUNCTION

CREATE OR REPLACE FUNCTION GET_DIRECT_REPORT_COUNT (
P_EMP_ID IN NUMBER
) RETURN NUMBER IS NUM_EM NUMBER;
BEGIN
  SELECT COUNT(EMPLOYEE_ID)
  INTO NUM_EM
  FROM EMPLOYEES
  WHERE MANAGER_ID = P_EMP_id;
  RETURN NUM_EM;
END;

-- PROCEDURE

CREATE OR REPLACE PROCEDURE BUILD_MANAGER_SUMMARY (
P_DEPT_ID IN NUMBER,
P_MANAGER_COUNT OUT NUMBER,
P_TOTAL_REPORTS OUT NUMBER
)

IS EMPLOYEE_FOUND NUMBER := 0;

BEGIN 

  P_MANAGER_COUNT := 0;
  P_TOTAL_REPORTS := 0;

  DELETE FROM MANAGER_SUMMARY
  WHERE DEPARTMENT_ID =  P_DEPT_ID;
  
  FOR EMPLOYEE_RECORD IN(
    SELECT EMPLOYEE_ID, 
    DEPARTMENT_ID, 
    FIRST_NAME || ' ' || LAST_NAME FULL_NAME,
    GET_DIRECT_REPORT_COUNT(EMPLOYEE_ID) REPORT_COUNT
    
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = P_DEPT_ID
  )
  
  LOOP
    EMPLOYEE_FOUND := 1;
    IF EMPLOYEE_RECORD.REPORT_COUNT > 0 THEN
    P_MANAGER_COUNT := P_MANAGER_COUNT + 1;
    P_TOTAL_REPORTS := P_TOTAL_REPORTS + EMPLOYEE_RECORD.REPORT_COUNT;
    INSERT INTO MANAGER_SUMMARY
    VALUES(EMPLOYEE_RECORD.EMPLOYEE_ID, EMPLOYEE_RECORD.DEPARTMENT_ID, EMPLOYEE_RECORD.FULL_NAME, EMPLOYEE_RECORD.REPORT_COUNT, USER, SYSDATE);
    END IF;
  
  END LOOP;
  
      IF EMPLOYEE_RECORD.REPORT_COUNT  = 0 THEN
    DBMS_OUTPUT.PUT_LINE(
        'No employees in department ' || P_DEPT_ID
    );
  END IF;
END;
/

DECLARE
  V_MANAGER_COUNT NUMBER;
  V_TOTAL_REPORTS NUMBER;
  BEGIN
    BUILD_MANAGER_SUMMARY(
      50,
      V_MANAGER_COUNT,
      V_TOTAL_REPORTS
      );
      
DBMS_OUTPUT.PUT_LINE(
    'Manager Count: ' || V_MANAGER_COUNT
);

DBMS_OUTPUT.PUT_LINE(
    'Total Reports: ' || V_TOTAL_REPORTS
);
  END;
/ 



-- TRIGGER

CREATE TABLE DEPT_RELOCATION_LOG (
DEPARTMENT_ID NUMBER,
OLD_LOCATION_ID NUMBER,
NEW_LOCATION_ID NUMBER,
OLD_CITY VARCHAR2(30),
NEW_CITY VARCHAR2(30),
RELOCATION_TYPE VARCHAR2(15),
RAISE_PCT NUMBER,
EMPLOYEES_AFFECTED NUMBER,
CHANGED_BY VARCHAR2(30),
CHANGED_ON DATE
);



CREATE OR REPLACE TRIGGER DEPT_RELOCATION
AFTER UPDATE OF LOCATION_ID ON DEPARTMENTS
FOR EACH ROW

DECLARE

    V_OLD_CITY      LOCATIONS.CITY%TYPE;
    V_NEW_CITY      LOCATIONS.CITY%TYPE;

    V_OLD_COUNTRY   LOCATIONS.COUNTRY_ID%TYPE;
    V_NEW_COUNTRY   LOCATIONS.COUNTRY_ID%TYPE;

    V_OLD_REGION    COUNTRIES.REGION_ID%TYPE;
    V_NEW_REGION    COUNTRIES.REGION_ID%TYPE;

    V_EMPLOYEES_AFFECTED NUMBER;
    V_RAISE_PCT          NUMBER;
    V_RELOCATION_TYPE    VARCHAR2(15);

BEGIN
  IF :OLD.LOCATION_ID <> :NEW.LOCATION_ID THEN
    SELECT L.CITY,
       L.COUNTRY_ID,
       C.REGION_ID
    INTO V_OLD_CITY,
       V_OLD_COUNTRY,
       V_OLD_REGION
    FROM LOCATIONS L
    JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID  
    WHERE L.LOCATION_ID = :OLD.LOCATION_ID;
    
     SELECT L.CITY,
       L.COUNTRY_ID,
       C.REGION_ID
    INTO V_NEW_CITY,
       V_NEW_COUNTRY,
       V_NEW_REGION
    FROM LOCATIONS L
    JOIN COUNTRIES C
    ON L.COUNTRY_ID = C.COUNTRY_ID  
    WHERE L.LOCATION_ID = :NEW.LOCATION_ID;
    
    
IF V_OLD_COUNTRY = V_NEW_COUNTRY THEN

    V_RELOCATION_TYPE := 'DOMESTIC';
    V_RAISE_PCT := 3;

ELSIF V_OLD_REGION = V_NEW_REGION THEN

    V_RELOCATION_TYPE := 'REGIONAL';
    V_RAISE_PCT := 8;

ELSE

    V_RELOCATION_TYPE := 'OVERSEAS';
    V_RAISE_PCT := 12;

END IF;

SELECT COUNT(*) 
INTO V_EMPLOYEES_AFFECTED
FROM EMPLOYEES
WHERE DEPARTMENT_ID = :OLD.DEPARTMENT_ID;

UPDATE EMPLOYEES
SET SALARY = ROUND(SALARY * (100 + V_RAISE_PCT) / 100, 2)
WHERE DEPARTMENT_ID = :OLD.DEPARTMENT_ID;




INSERT INTO DEPT_RELOCATION_LOG (
    DEPARTMENT_ID,
    OLD_LOCATION_ID,
    NEW_LOCATION_ID,
    OLD_CITY,
    NEW_CITY,
    RELOCATION_TYPE,
    RAISE_PCT,
    EMPLOYEES_AFFECTED,
    CHANGED_BY,
    CHANGED_ON
)
VALUES (
    :OLD.DEPARTMENT_ID,
    :OLD.LOCATION_ID,
    :NEW.LOCATION_ID,
    V_OLD_CITY,
    V_NEW_CITY,
    V_RELOCATION_TYPE,
    V_RAISE_PCT,
    V_EMPLOYEES_AFFECTED,
    USER,
    SYSDATE
);
END IF;
END;
/

UPDATE DEPARTMENTS
SET LOCATION_ID = 1500
WHERE DEPARTMENT_ID = 60;





SELECT line, position, text 
FROM all_errors 
WHERE name = 'DEPT_RELOCATION' 
  AND type = 'TRIGGER';
  
  SELECT trigger_name, status 
FROM user_triggers 
WHERE status = 'INVALID';

ALTER TRIGGER HR.SALARY_LIMIT DISABLE;
 
 ALTER TABLE EMPLOYEES DISABLE ALL TRIGGERS;
 
 ALTER TABLE EMPLOYEES ENABLE ALL TRIGGERS;
 
 
 SELECT DEPARTMENT_ID, OLD_LOCATION_ID,
NEW_LOCATION_ID, OLD_CITY, NEW_CITY,
RELOCATION_TYPE, RAISE_PCT,
EMPLOYEES_AFFECTED
FROM DEPT_RELOCATION_LOG
ORDER BY DEPARTMENT_ID;
