CREATE TABLE employees_copy AS
SELECT * FROM employees;
COMMIT;


CREATE OR REPLACE FUNCTION EXCHANGE_EMPLOYEES (
    MANAGER_ID1 IN EMPLOYEES.MANAGER_ID%TYPE,
    MANAGER_ID2 IN EMPLOYEES.MANAGER_ID%TYPE
)
RETURN VARCHAR2
IS
    -- variables
    V_EMP1 EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_SALARY1 EMPLOYEES.SALARY%TYPE;
    V_MANAGER1 EMPLOYEES.MANAGER_ID%TYPE;
    V_DEPT1 EMPLOYEES.DEPARTMENT_ID%TYPE;
    V_EMP2 EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_SALARY2 EMPLOYEES.SALARY%TYPE;
    V_MANAGER2 EMPLOYEES.MANAGER_ID%TYPE; 
    V_DEPT2 EMPLOYEES.DEPARTMENT_ID%TYPE;
    V_DIFF EMPLOYEES.SALARY%TYPE;
    V_NEW_SALARY1 EMPLOYEES.SALARY%TYPE;
    V_NEW_SALARY2 EMPLOYEES.SALARY%TYPE;

BEGIN

    SELECT EMPLOYEE_ID, SALARY, MANAGER_ID, DEPARTMENT_ID
    INTO V_EMP1, V_SALARY1, V_MANAGER1, V_DEPT1
    FROM EMPLOYEES_COPY
    WHERE MANAGER_ID = MANAGER_ID1
    ORDER BY SALARY
    FETCH FIRST 1 ROW ONLY;

    SELECT EMPLOYEE_ID, SALARY, MANAGER_ID, DEPARTMENT_ID
    INTO V_EMP2, V_SALARY2, V_MANAGER2, V_DEPT2
    FROM EMPLOYEES_COPY
    WHERE MANAGER_ID = MANAGER_ID2
    ORDER BY SALARY
    FETCH FIRST 1 ROW ONLY;
    
    V_DIFF := ABS(V_SALARY1 - V_SALARY2);
    
    V_NEW_SALARY1 := V_SALARY1 + 0.5 * V_DIFF;

    V_NEW_SALARY2 := V_SALARY2 + 0.5 * V_DIFF;
    
    
        DBMS_OUTPUT.PUT_LINE('========== BEFORE EXCHANGE ==========');

    DBMS_OUTPUT.PUT_LINE('Employee Information:');
    DBMS_OUTPUT.PUT_LINE('Employee ID: ' || V_EMP1);
    DBMS_OUTPUT.PUT_LINE('Salary: ' || V_SALARY1);
    DBMS_OUTPUT.PUT_LINE('Manager ID: ' || V_MANAGER1);
    DBMS_OUTPUT.PUT_LINE('Department ID: ' || V_DEPT1);

    DBMS_OUTPUT.PUT_LINE('-------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Employee Information:');
    DBMS_OUTPUT.PUT_LINE('Employee ID: ' || V_EMP2);
    DBMS_OUTPUT.PUT_LINE('Salary: ' || V_SALARY2);
    DBMS_OUTPUT.PUT_LINE('Manager ID: ' || V_MANAGER2);
    DBMS_OUTPUT.PUT_LINE('Department ID: ' || V_DEPT2);
    
    UPDATE EMPLOYEES_COPY
    SET MANAGER_ID = V_MANAGER2,
    DEPARTMENT_ID = V_DEPT2,
    SALARY = V_NEW_SALARY1
    WHERE EMPLOYEE_ID = V_EMP1;
    
    UPDATE EMPLOYEES_COPY
    SET MANAGER_ID = V_MANAGER1,
    DEPARTMENT_ID = V_DEPT1,
    SALARY = V_NEW_SALARY2
    WHERE EMPLOYEE_ID = V_EMP2; 
    
    
    DBMS_OUTPUT.PUT_LINE('========== AFTER EXCHANGE ==========');

    DBMS_OUTPUT.PUT_LINE('Employee Information:');
    DBMS_OUTPUT.PUT_LINE('Employee ID: ' || V_EMP1);
    DBMS_OUTPUT.PUT_LINE('Salary: ' || V_NEW_SALARY1);
    DBMS_OUTPUT.PUT_LINE('Manager ID: ' || V_MANAGER2);
    DBMS_OUTPUT.PUT_LINE('Department ID: ' || V_DEPT2);

    DBMS_OUTPUT.PUT_LINE('-------------------------------------');

    DBMS_OUTPUT.PUT_LINE('Employee Information:');
    DBMS_OUTPUT.PUT_LINE('Employee ID: ' || V_EMP2);
    DBMS_OUTPUT.PUT_LINE('Salary: ' || V_NEW_SALARY2);
    DBMS_OUTPUT.PUT_LINE('Manager ID: ' || V_MANAGER1);
    DBMS_OUTPUT.PUT_LINE('Department ID: ' || V_DEPT1);


    COMMIT;

    RETURN 'SUCCESS';
    

EXCEPTION

    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No data found.');
        RETURN 'FAILED';

    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('Too many rows.');
        RETURN 'FAILED';

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
        RETURN 'FAILED';
END;
/

DECLARE
    V_RESULT VARCHAR2(20);
BEGIN
    V_RESULT := EXCHANGE_EMPLOYEES(100, 145);

    DBMS_OUTPUT.PUT_LINE('RESULT: ' || V_RESULT);
END;
/


SELECT line, position, text 
FROM all_errors 
WHERE name = 'EXCHANGE_EMPLOYEES' 
AND type = 'FUNCTION';




-- PROCEDURE TEMPLATE

CREATE OR REPLACE PROCEDURE LOCATION_SALARY_REPORT
IS
    V_RANK NUMBER := 0;
    V_CITY_NAME LOCATIONS.CITY%TYPE;
    V_NUM_EMPLOYEES NUMBER;
    V_AVERAGE_SALARY NUMBER;
    V_JOB_TITLE JOBS.JOB_TITLE%TYPE;
    
    
    
BEGIN

    FOR R IN (
    SELECT COUNT(EMPLOYEE_ID), ROUND(AVG(SALARY), 2),
               (
               SELECT J.JOB_TITLE
               FROM EMPLOYEES E2
               JOIN DEPARTMENTS D2
                   ON E2.DEPARTMENT_ID = D2.DEPARTMENT_ID
               JOIN LOCATIONS L2
                   ON D2.LOCATION_ID = L2.LOCATION_ID
               JOIN JOBS J
                   ON E2.JOB_ID = J.JOB_ID
               WHERE L2.CITY = L.CITY
               ORDER BY E2.SALARY DESC
               FETCH FIRST 1 ROW ONLY
           ) AS HIGHEST_PAYING_JOB
    INTO V_NUM_EMPLOYEES, V_AVERAGE_SALARY
    FROM EMPLOYEES E
    JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    JOIN LOCATIONS L
    ON L.LOCATION_ID = D.LOCATION_ID
    GROUP BY L.CITY
    ORDER BY COUNT(E.EMPLOYEE_ID) ASC,
    AVG(E.SALARY) DESC;
    
    )
    LOOP

        V_RANK := V_RANK + 1;

    DBMS_OUTPUT.PUT_LINE(
        'Rank: ' || V_RANK ||
        ' City: ' || R.CITY ||
        ' Employees: ' || R.TOTAL_EMPLOYEES ||
        ' Average Salary: ' || R.AVG_SALARY ||
        ' Highest Paying Job: ' || R.HIGHEST_PAYING_JOB
    );

    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/





CREATE TABLE TRANSFERS (
    EMPLOYEE_ID NUMBER,
    EMPLOYEE_WORKING_INSTEAD_OF_HIM NUMBER,
    NEW_DEPARTMENT NUMBER,
    TRANSFER_DATE DATE
);




CREATE OR REPLACE TRIGGER EMPLOYEE_TRANSFER
AFTER UPDATE OF DEPARTMENT_ID
ON EMPLOYEES
FOR EACH ROW

DECLARE
    V_REPLACEMENT_ID       EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_REPLACEMENT_SALARY   EMPLOYEES.SALARY%TYPE;

    V_OLD_MANAGER_COUNT    NUMBER;
    V_NEW_MANAGER_ID       EMPLOYEES.EMPLOYEE_ID%TYPE;

BEGIN

    IF :OLD.MANAGER_ID IS NOT NULL THEN
    
      SELECT EMPLOYEE_ID, SALARY
      INTO V_REPLACEMENT_ID, V_REPLACEMENT_SALARY
      FROM EMPLOYEES
      WHERE MANAGER_ID = :OLD.MANAGER_ID AND EMPLOYEE_ID <> :OLD.EMPLOYEE_ID
      ORDER BY ABS(SALARY - OLD.SALARY)
      FETCH FIRST 1 ROW ONLY;

      UPDATE EMPLOYEES
      SET SALARY = V_REPLACEMENT_SALARY + 0.5 * :OLD.SALARY
      WHERE EMPLOYEE_ID = V_REPLACEMENT_ID;

SELECT COUNT(*)
INTO V_OLD_MANAGER_COUNT
FROM EMPLOYEES
WHERE MANAGER_ID = :OLD.MANAGER_ID;


SELECT M.EMPLOYEE_ID
INTO V_NEW_MANAGER_ID
FROM EMPLOYEES M
LEFT JOIN EMPLOYEES S
    ON M.EMPLOYEE_ID = S.MANAGER_ID
WHERE M.DEPARTMENT_ID = :NEW.DEPARTMENT_ID
GROUP BY M.EMPLOYEE_ID
ORDER BY ABS(
    COUNT(S.EMPLOYEE_ID) - V_OLD_MANAGER_COUNT
)
FETCH FIRST 1 ROW ONLY;
        
        
      UPDATE EMPLOYEES
        SET MANAGER_ID = V_NEW_MANAGER_ID
        WHERE EMPLOYEE_ID = :NEW.EMPLOYEE_ID;

    END IF;
    
    
        INSERT INTO TRANSFERS (
        EMPLOYEE_ID,
        EMPLOYEE_WORKING_INSTEAD_OF_HIM,
        NEW_DEPARTMENT,
        TRANSFER_DATE
    )
    VALUES (
        :NEW.EMPLOYEE_ID,
        V_REPLACEMENT_ID,
        :NEW.DEPARTMENT_ID,
        SYSDATE
    );

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No data found.');

    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);

END;
/

