1.

SELECT 
SUBSTR(JOB_ID, 4),
COUNT(*) emplyee_number
FROM EMPLOYEES
WHERE SALARY > 4000 AND COMMISSION_PCT IS NULL
GROUP BY SUBSTR(JOB_ID, 4)

-----------------------------------------------------

2.

SELECT 
EMPLOYEE_ID,
FIRST_NAME, 
LAST_NAME,
(SUBSTR(FIRST_NAME, 1, 1) || SUBSTR(LAST_NAME, 1, 1)) AS TAG
FROM EMPLOYEES
WHERE (SUBSTR(FIRST_NAME, 1, 1) = SUBSTR(LAST_NAME, 1, 1))
ORDER BY EMPLOYEE_ID


------------------------------------------------------------

3.


CREATE TABLE EMP_BONUS
(
BONUS_ID NUMBER PRIMARY KEY, 
EMPLOYEE_ID NUMBER,
BONUS_AMOUNT NUMBER NOT NULL CHECK (BONUS_AMOUNT > 0),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
)

INSERT INTO EMP_BONUS
VALUES (1001, 101, 10000)

------------------------------------------------------------

4.

SELECT 
EMPLOYEE_ID,
TO_CHAR(HIRE_DATE, 'MON') Hire_month,
CASE 
  WHEN COMMISSION_PCT IS NULL THEN 'No Commission'
  WHEN COMMISSION_PCT IS NOT NULL THEN TO_CHAR(COMMISSION_PCT)
  END AS Commision
FROM EMPLOYEES
WHERE LOWER(TRIM(TO_CHAR(HIRE_DATE, 'MONTH'))) IN ('december', 'january', 'february') AND SALARY > 8000
ORDER BY CASE
      WHEN EXTRACT(MONTH FROM HIRE_DATE) = 12 THEN 1
      WHEN EXTRACT(MONTH FROM HIRE_DATE) = 1 THEN 2
      WHEN EXTRACT(MONTH FROM HIRE_DATE) = 2 THEN 3
      END
      
      
------------------------------------------------------------

5.

SELECT MANAGER_ID,
SUM(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING SUM(SALARY) > 30000 AND (COUNT(*)) > 5
ORDER BY  SUM(SALARY) DESC

