1.

SELECT 
TO_CHAR(HIRE_DATE, 'MON') Month,
COUNT(*) employee_number
FROM EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'MON'), EXTRACT(MONTH FROM HIRE_DATE)
ORDER BY EXTRACT(MONTH FROM HIRE_DATE) ASC


-----------------------------------------------------

2.







----------------------------------------------------------

3.

CREATE TABLE PERFORMANCE_REVIEW
(
REVIEW_ID NUMBER PRIMARY KEY,
EMPLOYEE_ID NUMBER, 
REVIEW_YEAR DATE, 
RATING NUMBER CHECK (RATING BETWEEN 1 AND 5), 
REMARKS VARCHAR(100),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
)

INSERT INTO PERFORMANCE_REVIEW
VALUES (1001, 101, TO_DATE('2023', 'YYYY'), 1, 'NOT BAD')


-------------------------------------------------

4.

SELECT 
EMPLOYEE_ID, 
(FIRST_NAME || ' ' || LAST_NAME) FullName,
(LOWER(SUBSTR(FIRST_NAME, 1, 3)) || SUBSTR(PHONE_NUMBER, -3)) USER_ID
FROM EMPLOYEES
WHERE LENGTH(PHONE_NUMBER)  >= 10 AND DEPARTMENT_ID IN (50, 80)
ORDER BY LENGTH(FIRST_NAME) DESC

-------------------------------------------------

5.

SELECT 
JOB_ID,
(MAX(SALARY) - MIN(SALARY)) SALARY_GAP
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING (MAX(SALARY) - MIN(SALARY)) > 3000 AND (MAX(SALARY) + MIN(SALARY)) / 2 > 6000


















