1.

SELECT 
EMPLOYEE_ID,
(FIRST_NAME || ' ' || LAST_NAME)  Full_Name
FROM EMPLOYEES
WHERE LAST_NAME LIKE '%__son%'

-----------------------------------------------

2.

SELECT
TO_CHAR(HIRE_DATE, 'DAY') hire_day,
COUNT(*) total_hired
FROM EMPLOYEES
WHERE MOD(TO_NUMBER(TO_CHAR(HIRE_DATE, 'DDD')), 2) <> 0
GROUP BY TO_CHAR(HIRE_DATE, 'DAY')
HAVING ((MAX(SALARY) + MIN(SALARY)) / 2) > 7000 


-----------------------------------------------


3.


SELECT 
EMPLOYEE_ID,
CASE 
	WHEN SALARY > 10000 THEN 'High Fixed'
  WHEN SALARY >= 10000 THEN 'Standard Fixed'
  
  END AS income_status 

FROM EMPLOYEES


---------------------------------------------------

4.

CREATE TABLE YOUNG_EMPLOYEES AS
SELECT *
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 
            (SELECT MAX(EXTRACT(YEAR FROM HIRE_DATE)) FROM EMPLOYEES)


ALTER TABLE YOUNG_EMPLOYEES
MODIFY FIRST_NAME NOT NULL

ALTER TABLE YOUNG_EMPLOYEES
ADD CONSTRAINT uq_email UNIQUE(email)

ALTER TABLE YOUNG_EMPLOYEES
ADD CONSTRAINT ch_email CHECK(EMAIL LIKE '%@%')


ALTER TABLE YOUNG_EMPLOYEES
ADD CONSTRAINT salary_check CHECK (SALARY >= 2000)

ALTER  TABLE YOUNG_EMPLOYEES
DROP COLUMN  COMMISSION_PCT


-----------------------------------------

5.

ALTER TABLE EMPLOYEES
ADD salary_grade VARCHAR2(1)

ALTER TABLE EMPLOYEES
ADD CONSTRAINT ch_salary_grd
CHECK (salary_grade IN ('L', 'M', 'H'))

UPDATE EMPLOYEES
SET salary_grade = 
CASE
  WHEN SALARY < 7000 THEN 'L'
  WHEN SALARY BETWEEN 700 AND 1200 THEN 'M'
  WHEN SALARY > 1200 THEN 'H'
 END;


UPDATE EMPLOYEES
SET SALARY = SALARY + SALARY * 0.08
WHERE JOB_ID LIKE 'SA\_%' ESCAPE '\'
AND TO_CHAR(HIRE_DATE, 'MM') = '03'
