1.



SELECT 

  'Q' || CEIL(EXTRACT(MONTH FROM HIRE_DATE)/3) AS QUARTER,
  COUNT(*) AS EMPLOYEE_COUNT
  
FROM EMPLOYEES
GROUP BY 'Q' || CEIL(EXTRACT(MONTH FROM HIRE_DATE)/3)
ORDER BY 'Q' || CEIL(EXTRACT(MONTH FROM HIRE_DATE)/3);










---------------------------------------------------

2.

SELECT 
LPAD(FIRST_NAME || ' ' || LAST_NAME, 20) AS "Full Name"
FROM EMPLOYEES
ORDER BY LENGTH(FIRST_NAME || ' ' || LAST_NAME) ASC


---------------------------------------------------

3.

SELECT COUNTRY_ID,
STREET_ADDRESS || ' ' || CITY || ' ' || STATE_PROVINCE || '-' || POSTAL_CODE AS "ADDRESS"
FROM LOCATIONS
WHERE STREET_ADDRESS IS NOT NULL AND CITY IS NOT NULL AND STATE_PROVINCE IS NOT NULL AND POSTAL_CODE IS NOT NULL
ORDER BY COUNTRY_ID ASC, POSTAL_CODE DESC


---------------------------------------------------

4.

SELECT 
DEPARTMENT_ID,
JOB_ID,
-- ekhane kintu to char, trunc eigula behuda korsi
TO_CHAR(TRUNC(MIN(HIRE_DATE), 'DAY')),
TO_CHAR(TRUNC(MAX(HIRE_DATE), 'DAY')),
ROUND(AVG(SALARY), 2)
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL 
AND JOB_ID IS NOT NULL
AND HIRE_DATE IS NOT NULL
AND SALARY IS NOT NULL
GROUP BY DEPARTMENT_ID, JOB_ID
HAVING AVG(SALARY) > 8000
ORDER BY DEPARTMENT_ID


---------------------------------------------------

5.

SELECT 
FIRST_NAME || ' ' || LAST_NAME AS "Full Name",
HIRE_DATE
FROM EMPLOYEES
WHERE SUBSTR(LOWER(FIRST_NAME), 1, 1) NOT IN('a', 'e', 'i', 'o', 'u')
AND LOWER(LAST_NAME) NOT LIKE '%b%' AND TRIM(TO_CHAR(HIRE_DATE, 'MM')) = '11'
ORDER BY "Full Name"








