1.

SELECT 
SUBSTR(PHONE_NUMBER, 1, 3),
COUNT(*) NUM_EMPLOYEE
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) > 2005
GROUP BY SUBSTR(PHONE_NUMBER, 1, 3)

-------------------------------------------------

2.

SELECT EMPLOYEE_ID,
SALARY,
ABS(SALARY - ROUND(SALARY / 1000) * 1000) AS salary_diff
FROM EMPLOYEES


-------------------------------------------------


3.


CREATE TABLE EMP_TRAINING
(
TRAINING_ID NUMBER PRIMARY KEY, 
EMPLOYEE_ID NUMBER, 
TRAINING_NAME VARCHAR2(50) NOT NULL, 
REG_DATE DATE DEFAULT SYSDATE,
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
)

INSERT INTO EMP_TRAINING
VALUES ()


-------------------------------------------------


4.


SELECT
DEPARTMENT_ID,
TO_CHAR(SUM(SALARY * 12), '999,999,999') AS total_payout
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) > 2 AND MIN(SALARY) >= 2500


-----------------------------------------------

5.

SELECT EMPLOYEE_ID,
SUBSTR(UPPER(FIRST_NAME), 1, 2) || LENGTH(LAST_NAME) || SUBSTR(PHONE_NUMBER, -1)  "Security Code"
FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) > LENGTH(LAST_NAME)
ORDER BY LENGTH(SUBSTR(UPPER(FIRST_NAME), 1, 2) || LENGTH(LAST_NAME) || SUBSTR(PHONE_NUMBER, -1)) DESC




