1.

SELECT 
SUBSTR(JOB_ID, 4),
COUNT(*) emplyee_number
FROM EMPLOYEES
WHERE SALARY > 4000 AND COMMISSION_PCT IS NULL
GROUP BY SUBSTR(JOB_ID, 4)

-----------------------------------------------------

2.

SELECT 
EMPLOYEE_ID,
FIRST_NAME, 
LAST_NAME,
(SUBSTR(FIRST_NAME, 1, 1) || SUBSTR(LAST_NAME, 1, 1)) AS TAG
FROM EMPLOYEES
WHERE (SUBSTR(FIRST_NAME, 1, 1) = SUBSTR(LAST_NAME, 1, 1))
ORDER BY EMPLOYEE_ID


------------------------------------------------------------

3.


CREATE TABLE EMP_BONUS
(
BONUS_ID NUMBER PRIMARY KEY, 
EMPLOYEE_ID NUMBER,
BONUS_AMOUNT NUMBER NOT NULL CHECK (BONUS_AMOUNT > 0),
FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
)

INSERT INTO EMP_BONUS
VALUES (1001, 101, 10000)

------------------------------------------------------------

4.

SELECT 
EMPLOYEE_ID,
TO_CHAR(HIRE_DATE, 'MON') Hire_month,
CASE 
  WHEN COMMISSION_PCT IS NULL THEN 'No Commission'
  WHEN COMMISSION_PCT IS NOT NULL THEN TO_CHAR(COMMISSION_PCT)
  END AS Commision
FROM EMPLOYEES
WHERE LOWER(TRIM(TO_CHAR(HIRE_DATE, 'MONTH'))) IN ('december', 'january', 'february') AND SALARY > 8000
ORDER BY CASE
      WHEN EXTRACT(MONTH FROM HIRE_DATE) = 12 THEN 1
      WHEN EXTRACT(MONTH FROM HIRE_DATE) = 1 THEN 2
      WHEN EXTRACT(MONTH FROM HIRE_DATE) = 2 THEN 3
      END
      
      
------------------------------------------------------------

5.

SELECT MANAGER_ID,
SUM(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING SUM(SALARY) > 30000 AND (COUNT(*)) > 5
ORDER BY  SUM(SALARY) DESC


------------------------------------------------------------





SELECT
EMPLOYEE_ID,
SALARY,
CASE
  WHEN SALARY > 10000 THEN 'High Fixed'
  WHEN SALARY >= 10000 THEN 'Standard Fixed'
  END AS income_statues
FROM EMPLOYEES



CREATE TABLE YOUNG_EMPLOYEES AS 
SELECT * 
FROM EMPLOYEES
WHERE EXTRACT(YEAR FROM HIRE_DATE) = (
                        SELECT
                        MAX(EXTRACT(YEAR FROM HIRE_DATE)) FROM                         EMPLOYEES)



ALTER TABLE YOUNG_EMPLOYEES
MODIFY FIRST_NAME NOT NULL

ALTER TABLE YOUNG_EMPLOYEES
ADD CONSTRAINT check_email UNIQUE(email)

ALTER TABLE YOUNG_EMPLOYEES
ADD CONSTRAINT ch_email CHECK(EMAIL LIKE '%@%')

ALTER TABLE YOUNG_EMPLOYEES
ADD CONSTRAINT salary_check CHECK(SALARY >= 2000) 


ALTER TABLE YOUNG_EMPLOYEES
DROP COLUMN  COMMISSION_PCT 



ALTER TABLE EMPLOYEES
ADD salary_grade VARCHAR2(1)


ALTER TABLE EMPLOYEES
ADD CONSTRAINT chkkk CHECK(SALARY_GRADE IN ('L', 'M', 'H'))


UPDATE EMPLOYEES
SET SALARY_GRADE = CASE
            WHEN SALARY < 7000 THEN 'L'
            WHEN SALARY BETWEEN 7000 AND 12000 THEN 'M'
            WHEN SALARY > 12000 THEN 'H'
            END
    
    
SELECT SALARY, SALARY_GRADE FROM EMPLOYEES



UPDATE EMPLOYEES
SET SALARY = SALARY + SALARY * 0.08
WHERE JOB_ID LIKE 'SA\_%' ESCAPE '\' AND EXTRACT(MONTH FROM HIRE_DATE) = 3

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE 'SA\_%' ESCAPE '\'
AND TO_CHAR(HIRE_DATE, 'MM') = '03'