SELECT E.EMPLOYEE_ID, E.FIRST_NAME || ' ' || E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.SALARY > (
  SELECT AVG(SALARY)
  FROM EMPLOYEES
)
ORDER BY SALARY DESC


---------------------------------------------------------


SELECT E.EMPLOYEE_ID, E.FIRST_NAME || ' ' || E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY, J.JOB_TITLE
FROM EMPLOYEES E 
JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN JOBS J
ON E.JOB_ID = J.JOB_ID
WHERE E.SALARY = 
(
  SELECT MAX(E1.SALARY)
  FROM EMPLOYEES E1
  WHERE E.DEPARTMENT_ID = E1.DEPARTMENT_ID AND
    E1.SALARY < (
        SELECT MAX(E2.SALARY)
        FROM EMPLOYEES E2
        WHERE E.DEPARTMENT_ID = E2.DEPARTMENT_ID
      )
)

AND E.DEPARTMENT_ID IN 
(
  SELECT DEPARTMENT_ID 
  FROM EMPLOYEES 
  GROUP BY DEPARTMENT_ID 
  HAVING COUNT(EMPLOYEE_ID) >= 2
)
ORDER BY DEPARTMENT_NAME ASC,
          SALARY DESC


---------------------------------------------------------


SELECT LAST_NAME, SALARY, (
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS D 
WHERE E1.DEPARTMENT_ID = D.DEPARTMENT_ID
) "DEPARTMENT_NAME"
FROM EMPLOYEES E1
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM EMPLOYEES E2
    WHERE E1.DEPARTMENT_ID = E2.DEPARTMENT_ID
)


---------------------------------------------------------

SELECT E.EMPLOYEE_ID, E.FIRST_NAME || E.LAST_NAME, D.DEPARTMENT_NAME, E.SALARY,
CASE
  WHEN E.SALARY > 10000 THEN 'TOP TIER'
  ELSE 'STANDARD TIER'
  END
  
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IN
(
  SELECT DEPARTMENT_ID
  FROM EMPLOYEES 
  GROUP BY DEPARTMENT_ID 
  HAVING COUNT(EMPLOYEE_ID) > 3
  INTERSECT
  SELECT DEPARTMENT_ID
  FROM EMPLOYEES
  GROUP BY DEPARTMENT_ID
  HAVING AVG(SALARY) > 6000
)
ORDER BY DEPARTMENT_NAME ASC,
        SALARY DESC