SELECT EMPLOYEE_ID
FROM EMPLOYEES

MINUS

SELECT MANAGER_ID
FROM EMPLOYEES 
WHERE MANAGER_ID IS NOT NULL


SELECT LAST_NAME
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN
(
  SELECT EMPLOYEE_ID
  FROM EMPLOYEES
  MINUS
  SELECT MANAGER_ID
  FROM EMPLOYEES
  WHERE MANAGER_ID IS NOT NULL
)


SELECT LOCATION_ID FROM LOCATIONS 
MINUS 
SELECT LOCATION_ID FROM DEPARTMENTS



SELECT
    CASE
        WHEN SALARY < 5000 THEN 'C'
        WHEN SALARY < 10000 THEN 'B'
        WHEN SALARY < 15000 THEN 'A'
        ELSE 'A+'
    END AS "SALARY GRADE",
    COUNT(*)
FROM EMPLOYEES
GROUP BY
    CASE
        WHEN SALARY < 5000 THEN 'C'
        WHEN SALARY < 10000 THEN 'B'
        WHEN SALARY < 15000 THEN 'A'
        ELSE 'A+'
    END
ORDER BY "SALARY GRADE" ASC;



SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY > ANY (
  SELECT SALARY FROM EMPLOYEES E
  JOIN DEPARTMENTS D 
  ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
  WHERE LOWER(D.DEPARTMENT_NAME) = LOWER('SALES')
)


SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN
(
  SELECT AVG(SALARY) - 5000
  FROM EMPLOYEES 
  WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'SALES')
)
AND 
(
  SELECT AVG(SALARY) + 5000
  FROM EMPLOYEES
  WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME = 'SALES')
)