-- JOIN (ON condition and USING)

SELECT 
E.FIRST_NAME,
E.LAST_NAME,
D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- USING

SELECT 
E.FIRST_NAME,
E.LAST_NAME,
DEPARTMENT_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
USING(DEPARTMENT_ID);

-- last name of manager for each employee

SELECT
M.LAST_NAME "MANAGER",
-- E.LAST_NAME "EMPLOYEE",
COUNT(*)
FROM EMPLOYEES E JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY M.LAST_NAME;


--
SELECT 
E1.LAST_NAME,
COUNT(*) HIGHSAL
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON (E1.SALARY < E2.SALARY)
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
ORDER BY E1.LAST_NAME ASC;

