SELECT 
E1.LAST_NAME,
COUNT(*) HIGSAL
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON (E1.SALARY < E2.SALARY)
GROUP BY E1.EMPLOYEE_ID , E1.LAST_NAME
ORDER BY E1.LAST_NAME ASC;


SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID;


-- NUMBER OF EMPLOYEES MANAGED BY EACH EMPLOYEE
SELECT 
E1.LAST_NAME,
COUNT(E2.EMPLOYEE_ID) TOTAL
FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2
ON E1.EMPLOYEE_ID = E2.MANAGER_ID
GROUP BY E1.EMPLOYEE_ID, E1.LAST_NAME
HAVING COUNT(E2.EMPLOYEE_ID) > 0
ORDER BY COUNT(E2.EMPLOYEE_ID) ASC;


